export interface Project {
  id: string;
  name: string;
  path: string;
  description?: string;
  created_at: string;
  updated_at: string;
  is_git_repo?: boolean; // Cached git status, updated on check
}

export type CardType = 'feature' | 'bug' | 'task' | 'chore';
export type CardStatus = 'backlog' | 'todo' | 'in_progress' | 'review' | 'done';
export type ClaudeStatus = 'idle' | 'running' | 'waiting_input' | 'question' | 'error' | 'completed';
export type WorktreeStatus = 'none' | 'creating' | 'ready' | 'error' | 'cleaned';

export interface Card {
  id: string;
  project_id: string;
  title: string;
  description?: string;
  card_type: CardType;
  status: CardStatus;
  claude_status: ClaudeStatus;
  position: number;
  prompt?: string;
  created_at: string;
  updated_at: string;

  // Idea content (generated by Claude in Ideas phase)
  ideaSummary?: string;      // Short bullet-point summary
  ideaContent?: string;      // Full detailed idea discussion

  // Plan content (generated by Claude in Planning phase)
  planSummary?: string;      // Short bullet-point summary
  planContent?: string;      // Full detailed implementation plan

  // Git worktree integration
  branch_name?: string;
  worktree_path?: string;
  base_branch?: string;
  worktree_status?: WorktreeStatus;

  // Pull request info
  pr_url?: string;
  pr_number?: number;
}

export interface TerminalSession {
  id: string;
  card_id: string;
  project_path: string;
  is_active: boolean;
  claude_status: ClaudeStatus;
}

export interface TerminalOutput {
  session_id: string;
  data: number[];
}

export const CARD_TYPES: { value: CardType; label: string; color: string }[] = [
  { value: 'feature', label: 'Feature', color: 'bg-accent-green' },
  { value: 'bug', label: 'Bug', color: 'bg-accent-red' },
  { value: 'task', label: 'Task', color: 'bg-accent-blue' },
  { value: 'chore', label: 'Chore', color: 'bg-accent-purple' },
];

export const CARD_STATUSES: { value: CardStatus; label: string }[] = [
  { value: 'backlog', label: 'Ideas' },
  { value: 'todo', label: 'Planning' },
  { value: 'in_progress', label: 'Execution' },
  { value: 'review', label: 'Review' },
  { value: 'done', label: 'Done' },
];

export const CLAUDE_STATUS_CONFIG: Record<ClaudeStatus, { label: string; color: string }> = {
  idle: { label: 'Idle', color: 'bg-gray-500' },
  running: { label: 'Working', color: 'bg-blue-500' },
  waiting_input: { label: 'Waiting', color: 'bg-yellow-500' },
  question: { label: 'Question', color: 'bg-amber-500' },
  error: { label: 'Error', color: 'bg-red-500' },
  completed: { label: 'Done', color: 'bg-green-500' },
};

// ============================================
// Chat/Claude Headless Types
// ============================================

export type ChatMessageRole = 'user' | 'assistant' | 'tool' | 'system';

export interface ToolUsage {
  id: string;
  name: string;
  input: Record<string, unknown>;
  output?: string;
  status: 'pending' | 'running' | 'completed' | 'error';
  startedAt?: string;
  completedAt?: string;
}

export interface ChatMessage {
  id: string;
  role: ChatMessageRole;
  content: string;
  timestamp: string;
  isStreaming?: boolean;
  tools?: ToolUsage[];
}

export interface ClaudeSession {
  id: string;
  cardId: string;
  claudeSessionId?: string;
  projectPath: string;
  messages: ChatMessage[];
  status: ClaudeStatus;
  mode: SessionMode;
  isAlive: boolean;
  totalCostUsd: number;
  createdAt: string;
  lastActivity: string;
}

// Claude events from backend
export type ClaudeEventType =
  | 'session_started'
  | 'text_chunk'
  | 'tool_start'
  | 'tool_end'
  | 'status_changed'
  | 'session_completed'
  | 'session_error';

export interface ClaudeEvent {
  type: ClaudeEventType;
  session_id: string;
  // Fields vary by event type
  claude_session_id?: string;
  text?: string;
  tool_name?: string;
  tool_id?: string;
  tool_input?: Record<string, unknown>;
  success?: boolean;
  output?: string;
  status?: ClaudeStatus;
  result?: string;
  cost_usd?: number;
  error?: string;
  should_auto_transition?: boolean;
}

// ============================================
// Workflow State Machine Types
// ============================================

/** Session mode determines tool permissions and behavior */
export type SessionMode = 'planning' | 'execution' | 'review';

/** Panel mode determines which UI component to render */
export type PanelMode = 'ideas' | 'spec' | 'execution' | 'review' | 'readonly';

/** Card interaction mode for the workflow state machine */
export type CardInteractionMode = 'chat_only' | 'execution' | 'review' | 'readonly';

/** Map card status to session mode (tool permissions) */
export const STATUS_TO_SESSION_MODE: Record<CardStatus, SessionMode> = {
  backlog: 'planning',
  todo: 'planning',
  in_progress: 'execution',
  review: 'review',
  done: 'review',
};

/** Map card status to panel mode (UI component) */
export const STATUS_TO_PANEL_MODE: Record<CardStatus, PanelMode> = {
  backlog: 'ideas',
  todo: 'spec',
  in_progress: 'execution',
  review: 'review',
  done: 'readonly',
};

/** Map card status to interaction mode */
export const STATUS_TO_INTERACTION_MODE: Record<CardStatus, CardInteractionMode> = {
  backlog: 'chat_only',
  todo: 'chat_only',
  in_progress: 'execution',
  review: 'review',
  done: 'readonly',
};

/** Get panel mode for a given card status */
export function getPanelModeForStatus(status: CardStatus): PanelMode {
  return STATUS_TO_PANEL_MODE[status];
}

/** Get session mode for a given card status */
export function getSessionModeForStatus(status: CardStatus): SessionMode {
  return STATUS_TO_SESSION_MODE[status];
}

// ============================================
// Conversation Turn Types (Message Grouping)
// ============================================

/** A conversation turn groups a user message with its assistant response */
export interface ConversationTurn {
  id: string;
  userMessage: ChatMessage | null;
  assistantMessages: ChatMessage[];
  tools: ToolUsage[];
  timestamp: string;
  isActive: boolean;
}

// ============================================
// Workflow State Types
// ============================================

/** Tracks workflow state for each card */
export interface CardWorkflowState {
  cardId: string;
  interactionMode: CardInteractionMode;
  executionSessionId?: string;
  chatSessionId?: string;
  specDocument?: string;
  lastExecutionResult?: 'success' | 'error' | 'incomplete';
  reviewHighlighted: boolean;
  isBackgroundRunning: boolean;
}

/** Transition event for state machine */
export interface CardTransitionEvent {
  cardId: string;
  fromStatus: CardStatus;
  toStatus: CardStatus;
  triggeredBy: 'user_drag' | 'claude_completion' | 'manual_move';
  timestamp: string;
}

/** Guard conditions for transitions */
export interface TransitionGuard {
  canTransition: boolean;
  reason?: string;
  requiresConfirmation?: boolean;
  confirmationMessage?: string;
}

// ============================================
// Background Session Types
// ============================================

/** Track background running sessions */
export interface BackgroundSession {
  sessionId: string;
  cardId: string;
  projectPath: string;
  claudeSessionId?: string;
  status: ClaudeStatus;
  mode: SessionMode;
  startedAt: string;
}
